//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openai/api.dart';
import 'package:test/test.dart';

// tests for CreateClassificationRequest
void main() {
  // final instance = CreateClassificationRequest();

  group('test CreateClassificationRequest', () {
    // ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them.
    // String model
    test('to test the property `model`', () async {
      // TODO
    });

    // Query to be classified.
    // String query
    test('to test the property `query`', () async {
      // TODO
    });

    // A list of examples with labels, in the following format:  `[[\"The movie is so interesting.\", \"Positive\"], [\"It is quite boring.\", \"Negative\"], ...]`  All the label strings will be normalized to be capitalized.  You should specify either `examples` or `file`, but not both.
    // List<List<String>> examples (default value: const [])
    test('to test the property `examples`', () async {
      // TODO
    });

    // The ID of the uploaded file that contains training examples. See [upload file](/docs/api-reference/files/upload) for how to upload a file of the desired format and purpose.  You should specify either `examples` or `file`, but not both.
    // String file
    test('to test the property `file`', () async {
      // TODO
    });

    // The set of categories being classified. If not specified, candidate labels will be automatically collected from the examples you provide. All the label strings will be normalized to be capitalized.
    // List<String> labels (default value: const [])
    test('to test the property `labels`', () async {
      // TODO
    });

    // ID of the model to use for [Search](/docs/api-reference/searches/create). You can select one of `ada`, `babbage`, `curie`, or `davinci`.
    // String searchModel (default value: 'ada')
    test('to test the property `searchModel`', () async {
      // TODO
    });

    // What sampling `temperature` to use. Higher values mean the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.
    // num temperature (default value: 0)
    test('to test the property `temperature`', () async {
      // TODO
    });

    // Include the log probabilities on the `logprobs` most likely tokens, as well the chosen tokens. For example, if `logprobs` is 5, the API will return a list of the 5 most likely tokens. The API will always return the `logprob` of the sampled token, so there may be up to `logprobs+1` elements in the response.  The maximum value for `logprobs` is 5. If you need more than this, please contact us through our [Help center](https://help.openai.com) and describe your use case.  When `logprobs` is set, `completion` will be automatically added into `expand` to get the logprobs.
    // int logprobs
    test('to test the property `logprobs`', () async {
      // TODO
    });

    // The maximum number of examples to be ranked by [Search](/docs/api-reference/searches/create) when using `file`. Setting it to a higher value leads to improved accuracy but with increased latency and cost.
    // int maxExamples (default value: 200)
    test('to test the property `maxExamples`', () async {
      // TODO
    });

    // Modify the likelihood of specified tokens appearing in the completion.  Accepts a json object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this [tokenizer tool](/tokenizer?view=bpe) (which works for both GPT-2 and GPT-3) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.  As an example, you can pass `{\"50256\": -100}` to prevent the <|endoftext|> token from being generated.
    // Object logitBias
    test('to test the property `logitBias`', () async {
      // TODO
    });

    // If set to `true`, the returned JSON will include a \"prompt\" field containing the final prompt that was used to request a completion. This is mainly useful for debugging purposes.
    // bool returnPrompt (default value: false)
    test('to test the property `returnPrompt`', () async {
      // TODO
    });

    // A special boolean flag for showing metadata. If set to `true`, each document entry in the returned JSON will contain a \"metadata\" field.  This flag only takes effect when `file` is set.
    // bool returnMetadata (default value: false)
    test('to test the property `returnMetadata`', () async {
      // TODO
    });

    // If an object name is in the list, we provide the full information of the object; otherwise, we only provide the object ID. Currently we support `completion` and `file` objects for expansion.
    // List<Object> expand (default value: const [])
    test('to test the property `expand`', () async {
      // TODO
    });

    // A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).
    // String user
    test('to test the property `user`', () async {
      // TODO
    });
  });
}
