part of openai.api;

class CreateClassificationRequest {
  /* ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them. */
  String model = null;
/* Query to be classified. */
  String query = null;
/* A list of examples with labels, in the following format:  `[[\"The movie is so interesting.\", \"Positive\"], [\"It is quite boring.\", \"Negative\"], ...]`  All the label strings will be normalized to be capitalized.  You should specify either `examples` or `file`, but not both.  */
  List<List<String>> examples = [];
/* The ID of the uploaded file that contains training examples. See [upload file](/docs/api-reference/files/upload) for how to upload a file of the desired format and purpose.  You should specify either `examples` or `file`, but not both.  */
  String file = null;
/* The set of categories being classified. If not specified, candidate labels will be automatically collected from the examples you provide. All the label strings will be normalized to be capitalized. */
  List<String> labels = [];
/* ID of the model to use for [Search](/docs/api-reference/searches/create). You can select one of `ada`, `babbage`, `curie`, or `davinci`. */
  String searchModel = "ada";
/* What sampling `temperature` to use. Higher values mean the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer. */
  double temperature = 0;
/* Include the log probabilities on the `logprobs` most likely tokens, as well the chosen tokens. For example, if `logprobs` is 5, the API will return a list of the 5 most likely tokens. The API will always return the `logprob` of the sampled token, so there may be up to `logprobs+1` elements in the response.  The maximum value for `logprobs` is 5. If you need more than this, please contact us through our [Help center](https://help.openai.com) and describe your use case.  When `logprobs` is set, `completion` will be automatically added into `expand` to get the logprobs.  */
  int logprobs = null;
  //enum logprobsEnum {  };
/* The maximum number of examples to be ranked by [Search](/docs/api-reference/searches/create) when using `file`. Setting it to a higher value leads to improved accuracy but with increased latency and cost. */
  int maxExamples = 200;
/* Modify the likelihood of specified tokens appearing in the completion.  Accepts a json object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this [tokenizer tool](/tokenizer?view=bpe) (which works for both GPT-2 and GPT-3) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.  As an example, you can pass `{\"50256\": -100}` to prevent the <|endoftext|> token from being generated.  */
  Object logitBias = null;
/* If set to `true`, the returned JSON will include a \"prompt\" field containing the final prompt that was used to request a completion. This is mainly useful for debugging purposes. */
  bool returnPrompt = false;
/* A special boolean flag for showing metadata. If set to `true`, each document entry in the returned JSON will contain a \"metadata\" field.  This flag only takes effect when `file` is set.  */
  bool returnMetadata = false;
/* If an object name is in the list, we provide the full information of the object; otherwise, we only provide the object ID. Currently we support `completion` and `file` objects for expansion. */
  List<Object> expand = [];
/* A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).  */
  String user = null;

  CreateClassificationRequest();

  @override
  String toString() {
    return 'CreateClassificationRequest[model=$model, query=$query, examples=$examples, file=$file, labels=$labels, searchModel=$searchModel, temperature=$temperature, logprobs=$logprobs, maxExamples=$maxExamples, logitBias=$logitBias, returnPrompt=$returnPrompt, returnMetadata=$returnMetadata, expand=$expand, user=$user, ]';
  }

  CreateClassificationRequest.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    model = json['model'];
    query = json['query'];
    examples = List.listFromJson(json['examples']);
    file = json['file'];
    labels = (json['labels'] as List).map((item) => item as String).toList();
    searchModel = json['search_model'];
    temperature = json['temperature'];
    logprobs = json['logprobs'];
    maxExamples = json['max_examples'];
    logitBias = new Object.fromJson(json['logit_bias']);
    returnPrompt = json['return_prompt'];
    returnMetadata = json['return_metadata'];
    expand = Object.listFromJson(json['expand']);
    user = json['user'];
  }

  Map<String, dynamic> toJson() {
    return {
      'model': model,
      'query': query,
      'examples': examples,
      'file': file,
      'labels': labels,
      'search_model': searchModel,
      'temperature': temperature,
      'logprobs': logprobs,
      'max_examples': maxExamples,
      'logit_bias': logitBias,
      'return_prompt': returnPrompt,
      'return_metadata': returnMetadata,
      'expand': expand,
      'user': user
     };
  }

  static List<CreateClassificationRequest> listFromJson(List<dynamic> json) {
    return json == null ? new List<CreateClassificationRequest>() : json.map((value) => new CreateClassificationRequest.fromJson(value)).toList();
  }

  static Map<String, CreateClassificationRequest> mapFromJson(Map<String, Map<String, dynamic>> json) {
    var map = new Map<String, CreateClassificationRequest>();
    if (json != null && json.length > 0) {
      json.forEach((String key, Map<String, dynamic> value) => map[key] = new CreateClassificationRequest.fromJson(value));
    }
    return map;
  }
}
